# -*- coding: utf-8 -*-
"""Corrigir_Infosiga.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17f88j1iqpHqlzD1n-ec1pRDl26dE6uC4
"""

!pip install thefuzz python-Levenshtein # Instalar bibliotecas

# Monta o google drive no colab
from google.colab import drive
drive.mount('/content/drive')

# Bibliotecas
import pandas as pd
import os
import matplotlib.pyplot as plt
from google.colab import files
from google.colab import drive
import re
import unicodedata
from thefuzz import process, fuzz
import json

# Define o caminho do csv de sinistros do infosiga no gogle drive
caminho = '/content/drive/MyDrive/dados_infosiga/sinistros_2022-2026.csv'

# Define o caminho do csv de pessoas do infosiga no gogle drive
caminho_pessoas = '/content/drive/MyDrive/dados_infosiga/pessoas_2022-2026.csv'

registros = ['SINISTRO NAO FATAL', 'SINISTRO FATAL']
anos = [2022, 2023, 2024, 2025, 2026]

colunas_a_remover = [
    'tipo_local', 'latitude', 'longitude',
    'cod_ibge', 'administracao', 'conservacao',
    'circunscricao', 'regiao_administrativa' ,
    'qtd_gravidade_fatal', 'qtd_gravidade_grave',
    'qtd_gravidade_leve', 'qtd_gravidade_ileso', 'qtd_gravidade_nao_disponivel',
    'tp_sinistro_atropelamento', 'tp_sinistro_colisao_frontal', 'tp_sinistro_colisao_traseira',
    'tp_sinistro_colisao_lateral', 'tp_sinistro_colisao_transversal', 'tp_sinistro_colisao_outros',
    'tp_sinistro_choque', 'tp_sinistro_choque', 'tp_sinistro_capotamento',
    'tp_sinistro_engavetamento', 'tp_sinistro_tombamento', 'tp_sinistro_outros',
    'tp_sinistro_nao_disponivel'
    ]

#'qtd_pedestre', 'qtd_bicicleta', 'qtd_automovel',
#'qtd_onibus', 'qtd_caminhao', 'qtd_veic_outros',
#'qtd_veic_nao_disponivel','qtd_motocicleta'

try:
    # Adiciona o encoding para lidar com os acentos do Infosiga
    # Também adiciona o sep=';' caso o csv utilzar ;
    df = pd.read_csv(caminho, encoding='latin1', sep=';')

    # Filtro ano = 2025 e municipio = Ribeirão Preto e tipo de via = urbana
    df_ribeirao_2025 = df[
        (df['ano_sinistro'].isin(anos)) & (df['municipio'] == 'RIBEIRAO PRETO') & (df['tipo_via'] == 'VIAS URBANAS') &
        (df['tipo_registro'].isin(registros))
        ]

    df_ribeirao_2025 = df_ribeirao_2025.drop(columns=colunas_a_remover)

    # Exibe mensagem de sucesso e mostra 5 primeiros dados da tabela na tela
    print('Carga e Filtro Concluídos com sucesso!')

except UnicodeDecodeError:
    # Caso o latin1 falhe, usa outro padrão comum em arquivos brasileiros
    df = pd.read_csv(caminho, encoding='cp1252', sep=';')
    print('Carga concluída usando encoding alternativo (cp1252).')

# === join com a tabela pessoas ===

try:
    df_pessoas = pd.read_csv(caminho_pessoas, encoding='latin1', sep=';')

except UnicodeDecodeError:
    # Caso o latin1 falhe, usa outro padrão comum em arquivos brasileiros
    df_pessoas = pd.read_csv(caminho_pessoas, encoding='cp1252', sep=';')
    print('Carga concluída usando encoding alternativo (cp1252).')

df_pessoas_temp = df_pessoas[['id_sinistro', 'tipo_veiculo_vitima']].drop_duplicates(subset=['id_sinistro'])

df_ribeirao_2025 = pd.merge(
    df_ribeirao_2025,
    df_pessoas_temp,
    on='id_sinistro',
    how='left'
)

df_ribeirao_2025['tipo_veiculo_vitima'] = df_ribeirao_2025['tipo_veiculo_vitima'].fillna('PEDESTRE')

print('Coluna tipo_veiculo_vitima adicionada com sucesso!')
display(df_ribeirao_2025.head())

# --- Gerar Excel ---

import pandas as pd
import re
from thefuzz import process, fuzz
from google.colab import files

# Função de normalização (com a correção do espaço)
def normalizar_texto(texto):
    if pd.isna(texto): return ""
    texto = str(texto).upper().strip()
    texto = re.sub(r'\bAV\.?\b', 'AVENIDA', texto)
    texto = re.sub(r'\s+', ' ', texto)
    return texto

def corrigir_base_excel(df, coluna='logradouro', threshold=85):
    print("Iniciando normalização e análise de similares...")

    # Criar cópia do data frame
    df_clean = df.copy()

    # Aplica a normalização inicial (AV para AVENIDA e limpeza de espaços)
    df_clean[coluna] = df_clean[coluna].apply(normalizar_texto)

    # Contagem de frequência para definir o nome "correto" (o que mais aparece)
    contagem = df_clean[coluna].value_counts().to_dict()
    nomes_unicos = sorted(list(contagem.keys()), key=lambda x: contagem[x], reverse=True)

    # Dicionário de tradução: { 'NOME ERRADO': 'NOME CORRETO' }
    mapa_correcao = {}
    ja_processados = set()

    for nome in nomes_unicos:
        if nome in ja_processados or not nome:
            continue

        # Busca similares
        similares = process.extract(nome, nomes_unicos, scorer=fuzz.token_sort_ratio)

        for var_nome, score in similares:
            if score >= threshold and var_nome != nome and var_nome not in ja_processados:
                # Mapeia a variação para o nome mais frequente
                mapa_correcao[var_nome] = nome
                ja_processados.add(var_nome)

        ja_processados.add(nome)

    # 2. Aplica a correção em massa no DataFrame
    # O comando .replace substitui os valores baseados no dicionário
    df_clean[coluna] = df_clean[coluna].replace(mapa_correcao)

    print(f"Correção concluída. {len(mapa_correcao)} variações foram unificadas.")
    return df_clean

# --- Execução do Processo ---

# 1. Gera o DataFrame corrigido
df_final = corrigir_base_excel(df_ribeirao_2025)

# 2. Salva em Excel (usando o motor openpyxl)
nome_excel = "infosiga_ribeirao_2025_corrigido.xlsx"
df_final.to_excel(nome_excel, index=False)

# 3. Baixa o arquivo
print("Gerando arquivo Excel...")
files.download(nome_excel)

# --- Download de relatório em JSON ---

import pandas as pd
import json
import re
from thefuzz import process, fuzz
from google.colab import files

def normalizar_texto(texto):
    if pd.isna(texto): return ""
    texto = str(texto).upper().strip()
    # Substitui "AV " ou "AV." por "AVENIDA " (usando regex para precisão)
    texto = re.sub(r'\bAV\.?\b', 'AVENIDA', texto)
    # Remove espaços duplos que podem surgir na substituição
    texto = re.sub(r'\s+', ' ', texto)
    return texto

def analisar_logradouros_json(df, coluna='logradouro', threshold=85):
    # 1. Pré-processamento e Contagem
    df_temp = df.copy()
    df_temp[coluna] = df_temp[coluna].apply(normalizar_texto)

    contagem = df_temp[coluna].value_counts().to_dict()
    nomes_unicos = list(contagem.keys())

    relatorio_json = []
    ja_processados = set()

    # Ordena pelos mais frequentes para garantir que o "certo" seja o líder do grupo
    nomes_ordenados = sorted(nomes_unicos, key=lambda x: contagem[x], reverse=True)

    for nome in nomes_ordenados:
        if nome in ja_processados or not nome:
            continue

        # Busca similares
        similares = process.extract(nome, nomes_unicos, scorer=fuzz.token_sort_ratio)

        # Filtra variações
        variacoes = [
            {
                "variacao": res[0],
                "frequencia": contagem[res[0]],
                "score_similaridade": res[1]
            }
            for res in similares
            if res[1] >= threshold and res[0] != nome and res[0] not in ja_processados
        ]

        if variacoes:
            # Estrutura o grupo de erro
            grupo = {
                "nome_principal_sugerido": nome,
                "frequencia_total_principal": contagem[nome],
                "variacoes_detectadas": variacoes
            }
            relatorio_json.append(grupo)

            # Marca todos do grupo como processados
            for v in variacoes:
                ja_processados.add(v["variacao"])

        ja_processados.add(nome)

    return relatorio_json

# --- Execução ---

# 1. Aplica a análise
resultado_json = analisar_logradouros_json(df_ribeirao_2025)

# 2. Salva e baixa o arquivo JSON
nome_arquivo_json = "analise_logradouros_ribeirao.json"
with open(nome_arquivo_json, "w", encoding="utf-8") as f:
    json.dump(resultado_json, f, ensure_ascii=False, indent=4)

print(f"Análise concluída! {len(resultado_json)} grupos de divergência encontrados.")
files.download(nome_arquivo_json)

import pandas as pd
from google.colab import files

# 1. Preparação dos dados: remove espaços extras e padroniza para minúsculas
df_final['logradouro_clean'] = df_final['logradouro'].astype(str).str.strip().str.lower()

# 2. Definição dos filtros de prefixo
prefixos_avenida = ('av', 'avenida', 'av.', 'ave')
prefixos_rua = ('r', 'rua', 'r.', 'ruas')

# 3. Separação dos DataFrames
df_avenidas = df_final[df_final['logradouro_clean'].str.startswith(prefixos_avenida)]
df_ruas = df_final[df_final['logradouro_clean'].str.startswith(prefixos_rua)]

# O que não for avenida nem rua cai em "Outros"
df_outros = df_final[~df_final['logradouro_clean'].str.startswith(prefixos_avenida + prefixos_rua)]

# 4. Gera as contagens ordenadas
contagem_avenidas = df_avenidas['logradouro_clean'].value_counts()
contagem_ruas = df_ruas['logradouro_clean'].value_counts()
contagem_outros = df_outros['logradouro_clean'].value_counts()

# 5. Escrita no arquivo TXT com separação por blocos
nome_arquivo = 'relatorio_logradouros_categorizado.txt'

with open(nome_arquivo, 'w', encoding='utf-8') as f:
    f.write("=== CONTAGEM DE AVENIDAS ===\n")
    for log, total in contagem_avenidas.items():
        f.write(f"{log}: {total}\n")

    f.write("\n=== CONTAGEM DE RUAS ===\n")
    for log, total in contagem_ruas.items():
        f.write(f"{log}: {total}\n")

    f.write("\n=== OUTROS (NÃO IDENTIFICADOS) ===\n")
    for log, total in contagem_outros.items():
        f.write(f"{log}: {total}\n")

# 6. Download automático
files.download(nome_arquivo)

print(f"Relatório categorizado gerado com sucesso!")

# === JUNTANDO OS DATA FRAMES DE 2015 - 2021 ATÉ 2022 - 2026

import pandas as pd

# 1. Caminhos dos arquivos
caminho_antigo = '/content/drive/MyDrive/dados_infosiga/sinistros_2015-2021.csv'
caminho_novo = '/content/drive/MyDrive/dados_infosiga/sinistros_2022-2026.csv'

# Configurações de leitura (ajustadas para o padrão do Infosiga)
params = {'encoding': 'latin1', 'sep': ';', 'low_memory': False}

anos = [2020,
        2021,
        2022,
        2023,
        2024,
        2025,
        2026]

try:
    # 2. Carregar os dois arquivos
    df_15_21 = pd.read_csv(caminho_antigo, **params)
    df_22_26 = pd.read_csv(caminho_novo, **params)

    # 3. Concatenar (unir) as tabelas
    # axis=0 indica que queremos empilhar as linhas
    df_total = pd.concat([df_15_21, df_22_26], axis=0, ignore_index=True)

    # 4. Aplicar seus filtros no DataFrame unificado
    registros = ['SINISTRO NAO FATAL', 'SINISTRO FATAL']

    # Exemplo: filtrando Ribeirão Preto e Vias Urbanas em todo o histórico
    df_filtrado = df_total[
        (df_total['municipio'] == 'RIBEIRAO PRETO') &
        (df_total['ano_sinistro'].isin(anos)) &
        (df_total['tipo_via'] == 'VIAS URBANAS') &
        (df_total['tipo_registro'].isin(registros))
    ]

    # Remover as colunas que você definiu anteriormente
    df_final = df_filtrado.drop(columns=colunas_a_remover, errors='ignore')

    print(f"União concluída! Total de registros: {len(df_final)}")
    display(df_final.head())

except Exception as e:
    print(f"Erro ao processar arquivos: {e}")

    # =================================================== Gerar Excel ==========================================================

import pandas as pd
import re
from thefuzz import process, fuzz
from google.colab import files

# 1. Função de normalização (com a correção do espaço)
def normalizar_texto(texto):
    if pd.isna(texto): return ""
    texto = str(texto).upper().strip()
    texto = re.sub(r'\bAV\.?\b', 'AVENIDA', texto)
    texto = re.sub(r'\s+', ' ', texto)
    return texto

def corrigir_base_excel(df, coluna='logradouro', threshold=85):
    print("Iniciando normalização e análise de similares...")

    # Criar cópia do data frame
    df_clean = df.copy()

    # Aplica a normalização inicial (AV para AVENIDA e limpeza de espaços)
    df_clean[coluna] = df_clean[coluna].apply(normalizar_texto)

    # Contagem de frequência para definir o nome "correto" (o que mais aparece)
    contagem = df_clean[coluna].value_counts().to_dict()
    nomes_unicos = sorted(list(contagem.keys()), key=lambda x: contagem[x], reverse=True)

    # Dicionário de tradução: { 'NOME ERRADO': 'NOME CORRETO' }
    mapa_correcao = {}
    ja_processados = set()

    for nome in nomes_unicos:
        if nome in ja_processados or not nome:
            continue

        # Busca similares
        similares = process.extract(nome, nomes_unicos, scorer=fuzz.token_sort_ratio)

        for var_nome, score in similares:
            if score >= threshold and var_nome != nome and var_nome not in ja_processados:
                # Mapeia a variação para o nome mais frequente
                mapa_correcao[var_nome] = nome
                ja_processados.add(var_nome)

        ja_processados.add(nome)

    # 2. Aplica a correção em massa no DataFrame
    # O comando .replace substitui os valores baseados no dicionário
    df_clean[coluna] = df_clean[coluna].replace(mapa_correcao)

    print(f"Correção concluída. {len(mapa_correcao)} variações foram unificadas.")
    return df_clean

# --- Execução do Processo ---

# 1. Gera o DataFrame corrigido usando o DF que veio da união (pd.concat)
# Certifique-se de que o nome da variável é df_final (ou o nome que você deu no concat)
df_limpo_e_unificado = corrigir_base_excel(df_final)

# 2. Salva em Excel
nome_excel = "infosiga_ribeirao_completo_corrigido.xlsx"
df_limpo_e_unificado.to_excel(nome_excel, index=False)

# 3. Baixa o arquivo
files.download(nome_excel)

# ===================================================== Download de relatório em JSON ===========================================================

import pandas as pd
import json
import re
from thefuzz import process, fuzz
from google.colab import files

def normalizar_texto(texto):
    if pd.isna(texto): return ""
    texto = str(texto).upper().strip()
    # Substitui "AV " ou "AV." por "AVENIDA " (usando regex para precisão)
    texto = re.sub(r'\bAV\.?\b', 'AVENIDA', texto)
    # Remove espaços duplos que podem surgir na substituição
    texto = re.sub(r'\s+', ' ', texto)
    return texto

def analisar_logradouros_json(df, coluna='logradouro', threshold=85):
    # 1. Pré-processamento e Contagem
    df_temp = df.copy()
    df_temp[coluna] = df_temp[coluna].apply(normalizar_texto)

    contagem = df_temp[coluna].value_counts().to_dict()
    nomes_unicos = list(contagem.keys())

    relatorio_json = []
    ja_processados = set()

    # Ordena pelos mais frequentes para garantir que o "certo" seja o líder do grupo
    nomes_ordenados = sorted(nomes_unicos, key=lambda x: contagem[x], reverse=True)

    for nome in nomes_ordenados:
        if nome in ja_processados or not nome:
            continue

        # Busca similares
        similares = process.extract(nome, nomes_unicos, scorer=fuzz.token_sort_ratio)

        # Filtra variações
        variacoes = [
            {
                "variacao": res[0],
                "frequencia": contagem[res[0]],
                "score_similaridade": res[1]
            }
            for res in similares
            if res[1] >= threshold and res[0] != nome and res[0] not in ja_processados
        ]

        if variacoes:
            # Estrutura o grupo de erro
            grupo = {
                "nome_principal_sugerido": nome,
                "frequencia_total_principal": contagem[nome],
                "variacoes_detectadas": variacoes
            }
            relatorio_json.append(grupo)

            # Marca todos do grupo como processados
            for v in variacoes:
                ja_processados.add(v["variacao"])

        ja_processados.add(nome)

    return relatorio_json

# --- Execução ---

# 1. Aplica a análise
resultado_json = analisar_logradouros_json(df_limpo_e_unificado)

# 2. Salva e baixa o arquivo JSON
nome_arquivo_json = "analise_logradouros_ribeirao.json"
with open(nome_arquivo_json, "w", encoding="utf-8") as f:
    json.dump(resultado_json, f, ensure_ascii=False, indent=4)

print(f"Análise concluída! {len(resultado_json)} grupos de divergência encontrados.")
files.download(nome_arquivo_json)