# -*- coding: utf-8 -*-
"""infosiga.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UQ4Hb_i8fUE6jiECn0F8X2jQUjryhx2_
"""

!pip install thefuzz python-Levenshtein # Instalar bibliotecas

# Monta o google drive no colab
from google.colab import drive
drive.mount('/content/drive')

# Importa a biblioteca Pandas
import pandas as pd

import os

# Biblioteca para corrigir nomes com digitação errada
from thefuzz import process

# Biblioteca para baixar arquivos no Colab
from google.colab import files

from google.colab import drive

# 2. Define o caminho do csv do infosiga no gogle drive
caminho = '/content/drive/MyDrive/dados_infosiga/sinistros_2022-2025.csv'

try:
    # Adiciona o encoding para lidar com os acentos do Infosiga
    # Também adiciona o sep=';' caso o csv utilzar ;
    df = pd.read_csv(caminho, encoding='latin1', sep=';')

    # Filtro ano = 2025 e municipio = Ribeirão Preto e tipo de via = urbana
    df_ribeirao_2025 = df[(df['ano_sinistro'] == 2025) & (df['municipio'] == 'RIBEIRAO PRETO') & (df['tipo_via'] == 'VIAS URBANAS')]

    # Exibe mensagem de sucesso e mostra 5 primeiros dados da tabela na tela
    print('Carga e Filtro Concluídos com sucesso!')
    display(df_ribeirao_2025.head())

except UnicodeDecodeError:
    # Caso o latin1 falhe, usa outro padrão comum em arquivos brasileiros
    df = pd.read_csv(caminho, encoding='cp1252', sep=';')
    print('Carga concluída usando encoding alternativo (cp1252).')

import pandas as pd
from thefuzz import process, fuzz
import google.colab.files as files

# 1. Carregar o arquivo

def analisar_logradouros(df, coluna='logradouro', threshold=85):
    # Limpeza básica: remove duplicatas exatas e valores nulos
    nomes_unicos = df[coluna].dropna().unique().tolist()

    erros_encontrados = []
    ja_processados = set()

    for nome in nomes_unicos:
        if nome in ja_processados:
            continue

        # Busca nomes similares que não sejam o próprio nome
        similares = process.extract(nome, nomes_unicos, scorer=fuzz.token_sort_ratio)

        # Filtra apenas os que têm alta similaridade mas não são idênticos
        possiveis_erros = [res[0] for res in similares if res[1] >= threshold and res[0] != nome]

        if possiveis_erros:
            # Registra o grupo de erros
            linha = f"Principal: {nome} | Possíveis variações ({len(possiveis_erros)}): {', '.join(possiveis_erros)}"
            erros_encontrados.append(linha)

            # Adiciona ao set para não repetir a análise com as variações
            for p in possiveis_erros:
                ja_processados.add(p)
            ja_processados.add(nome)

    return erros_encontrados

# Execução do processo
resultado = analisar_logradouros(df_ribeirao_2025)

# 3. Gerar e baixar o arquivo .txt
nome_arquivo = "erros_logradouro_ribeirao.txt"
with open(nome_arquivo, "w", encoding="utf-8") as f:
    f.write("RELATÓRIO DE POSSÍVEIS ERROS DE DIGITAÇÃO - LOGRADOUROS\n")
    f.write("="*60 + "\n")
    for item in resultado:
        f.write(item + "\n")

files.download(nome_arquivo)

# --- Download de relatório em JSON ---

import pandas as pd
import json
import re
from thefuzz import process, fuzz
from google.colab import files

def normalizar_texto(texto):
    if pd.isna(texto): return ""
    texto = str(texto).upper().strip()
    # Substitui "AV " ou "AV." por "AVENIDA " (usando regex para precisão)
    texto = re.sub(r'\bAV\.?\b', 'AVENIDA', texto)
    # Remove espaços duplos que podem surgir na substituição
    texto = re.sub(r'\s+', ' ', texto)
    return texto

def analisar_logradouros_json(df, coluna='logradouro', threshold=85):
    # 1. Pré-processamento e Contagem
    df_temp = df.copy()
    df_temp[coluna] = df_temp[coluna].apply(normalizar_texto)

    contagem = df_temp[coluna].value_counts().to_dict()
    nomes_unicos = list(contagem.keys())

    relatorio_json = []
    ja_processados = set()

    # Ordena pelos mais frequentes para garantir que o "certo" seja o líder do grupo
    nomes_ordenados = sorted(nomes_unicos, key=lambda x: contagem[x], reverse=True)

    for nome in nomes_ordenados:
        if nome in ja_processados or not nome:
            continue

        # Busca similares
        similares = process.extract(nome, nomes_unicos, scorer=fuzz.token_sort_ratio)

        # Filtra variações
        variacoes = [
            {
                "variacao": res[0],
                "frequencia": contagem[res[0]],
                "score_similaridade": res[1]
            }
            for res in similares
            if res[1] >= threshold and res[0] != nome and res[0] not in ja_processados
        ]

        if variacoes:
            # Estrutura o grupo de erro
            grupo = {
                "nome_principal_sugerido": nome,
                "frequencia_total_principal": contagem[nome],
                "variacoes_detectadas": variacoes
            }
            relatorio_json.append(grupo)

            # Marca todos do grupo como processados
            for v in variacoes:
                ja_processados.add(v["variacao"])

        ja_processados.add(nome)

    return relatorio_json

# --- Execução ---

# 1. Aplica a análise
resultado_json = analisar_logradouros_json(df_ribeirao_2025)

# 2. Salva e baixa o arquivo JSON
nome_arquivo_json = "analise_logradouros_ribeirao.json"
with open(nome_arquivo_json, "w", encoding="utf-8") as f:
    json.dump(resultado_json, f, ensure_ascii=False, indent=4)

print(f"Análise concluída! {len(resultado_json)} grupos de divergência encontrados.")
files.download(nome_arquivo_json)

import pandas as pd
import re
from thefuzz import process, fuzz
from google.colab import files

# 1. Função de normalização (com a correção do espaço!)
def normalizar_texto(texto):
    if pd.isna(texto): return ""
    texto = str(texto).upper().strip()
    texto = re.sub(r'\bAV\.?\b', 'AVENIDA', texto)
    texto = re.sub(r'\s+', ' ', texto) # Correção do 's' para espaço
    return texto

def corrigir_base_excel(df, coluna='logradouro', threshold=85):
    print("Iniciando normalização e análise de similares...")

    # Criamos uma cópia para não estragar o dataframe original prematuramente
    df_clean = df.copy()

    # Aplica a normalização inicial (AV para AVENIDA e limpeza de espaços)
    df_clean[coluna] = df_clean[coluna].apply(normalizar_texto)

    # Contagem de frequência para definir o nome "correto" (o que mais aparece)
    contagem = df_clean[coluna].value_counts().to_dict()
    nomes_unicos = sorted(list(contagem.keys()), key=lambda x: contagem[x], reverse=True)

    # Dicionário de tradução: { 'NOME ERRADO': 'NOME CORRETO' }
    mapa_correcao = {}
    ja_processados = set()

    for nome in nomes_unicos:
        if nome in ja_processados or not nome:
            continue

        # Busca similares
        similares = process.extract(nome, nomes_unicos, scorer=fuzz.token_sort_ratio)

        for var_nome, score in similares:
            if score >= threshold and var_nome != nome and var_nome not in ja_processados:
                # Mapeia a variação para o nome mais frequente
                mapa_correcao[var_nome] = nome
                ja_processados.add(var_nome)

        ja_processados.add(nome)

    # 2. Aplica a correção em massa no DataFrame
    # O comando .replace substitui os valores baseados no dicionário
    df_clean[coluna] = df_clean[coluna].replace(mapa_correcao)

    print(f"Correção concluída. {len(mapa_correcao)} variações foram unificadas.")
    return df_clean

# --- Execução do Processo ---

# 1. Gera o DataFrame corrigido
df_final = corrigir_base_excel(df_ribeirao_2025)

# 2. Salva em Excel (usando o motor openpyxl)
nome_excel = "infosiga_ribeirao_2025_corrigido.xlsx"
df_final.to_excel(nome_excel, index=False)

# 3. Baixa o arquivo
print("Gerando arquivo Excel...")
files.download(nome_excel)